# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"XMLDetectionDataset": "00_dataset.ipynb",
         "CLASSES": "00_dataset.ipynb",
         "XMLDetectionDataModule": "00_dataset.ipynb",
         "bbox_iou": "02_metrics.ipynb",
         "SingleBoxDetector": "01_model.ipynb",
         "COCO_INSTANCE_CATEGORY_NAMES": "01_model.ipynb",
         "name2idx": "01_model.ipynb",
         "sports_ball_ID": "01_model.ipynb",
         "TorchVisionDetector": "01_model.ipynb",
         "hungarian_loss": "02_metrics.ipynb",
         "random_bbox": "03_utils.ipynb",
         "visualize_bbox": "03_utils.ipynb",
         "visualize": "03_utils.ipynb"}

modules = ["dataset.py",
           "model.py",
           "metrics.py",
           "utils.py"]

doc_url = "https://AtomScott.github.io/detection_nbdev/"

git_url = "https://github.com/AtomScott/detection_nbdev/tree/master/"

def custom_doc_links(name): return None
